/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ServiziLazyImport = createFileRoute('/servizi')()
const RicambiLazyImport = createFileRoute('/ricambi')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ServiziLazyRoute = ServiziLazyImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/servizi.lazy').then((d) => d.Route))

const RicambiLazyRoute = RicambiLazyImport.update({
  id: '/ricambi',
  path: '/ricambi',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ricambi.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/ricambi': {
      id: '/ricambi'
      path: '/ricambi'
      fullPath: '/ricambi'
      preLoaderRoute: typeof RicambiLazyImport
      parentRoute: typeof rootRoute
    }
    '/servizi': {
      id: '/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof ServiziLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/ricambi': typeof RicambiLazyRoute
  '/servizi': typeof ServiziLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/ricambi': typeof RicambiLazyRoute
  '/servizi': typeof ServiziLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/ricambi': typeof RicambiLazyRoute
  '/servizi': typeof ServiziLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ricambi' | '/servizi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ricambi' | '/servizi'
  id: '__root__' | '/' | '/ricambi' | '/servizi'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  RicambiLazyRoute: typeof RicambiLazyRoute
  ServiziLazyRoute: typeof ServiziLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  RicambiLazyRoute: RicambiLazyRoute,
  ServiziLazyRoute: ServiziLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ricambi",
        "/servizi"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/ricambi": {
      "filePath": "ricambi.lazy.tsx"
    },
    "/servizi": {
      "filePath": "servizi.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
